### ISSUE TITLE
Volumesnapshot object created for invalid PVC name

### ISSUE THREAD

**Issue by hr1sh1kesh** [libopenstorage/stork#15]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:
Using an invalid PVC name still creates the Volumesnapshot object. It doesnt create the Volumesnapshotdata object which is correct but the volumesnapshot object is created. The message when you apply the snapshot spec also says that the snapshot is created. 
This is misleading to the end user

**What you expected to happen**:
The k8s object creation of volumesnapshot should fail.  

**How to reproduce it (as minimally and precisely as possible)**:
Use the following spec on a k8s cluster. It wouldnt find the PVC with its name. 
 
```
apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: data-randomizer-0
  namespace: default
spec:
  persistentVolumeClaimName: data-storage-0
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
