### ISSUE TITLE
Add support for ClusterDomains

### ISSUE THREAD

**Issue by adityadani** [libopenstorage/stork#294]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What you expected to happen**:
Introduce the notion of ClusterDomains in stork. Certain storage providers like Portworx can have their clusters stretch across multiple Kubernetes or Openshift clusters. These clusters can act as different failure domains or metro domains. 

In an event where a Kubernetes cluster goes down, stork can help migrate application from it to another paired Kubernetes cluster. Stork will provide a way to activate or deactivate a particular cluster domain, so that applications from a deactivated cluster domain can failover to an active one.

We will introduce two new CRDs:

**ClusterDomainsStatus**

The ClusterDomainsStatus CRD will be used to get the status of all metro domains in the cluster. When Metro is enabled:
the following CRD will be added to the PX install spec 
It will be automatically applied in the cluster.

```
apiVersion: libopenstorage.stork.org/v1alpha1
kind: ClusterDomainsStatus
metadata:
 name: <cluster-name>
 namespace: kube-system
```

We can use storkctl to fetch the status of all metro domains

```
storkctl get clusterdomainsstatus -n kube-system

NAME             ACTIVE       INACTIVE    LAST UPDATED           CREATED
<cluster-name>   Zone1,Zone2  Zone3       18 Mar 19 10:34 UTC    16 Mar 19 20:04 UTC
  ```             
                

**ClusterDomainsUpdate**
The ClusterDomainsUpdate CRD will be used to activate or deactivate a metro domain in the cluster.

```
apiVersion: libopenstorage.stork.org/v1alpha1
kind: ClusterDomainsUpdate
metadata:
 name: activatezone1
 namespace: kube-system
spec:
  # Name of the metro domain that needs to be activated/deactivated
  metrodomain: Zone1
  # Set to true to activate metro domain
  # Set to false to deactivate metro domain
  active: true
```

We can use storkctl to fetch the status of the updates

```
storkctl get clusterdomainsupdate -n kube-system

NAME             METRODOMAIN STATE     STATUS     CREATED
activatezone1    Zone1       Active    DONE       16 Mar 19 20:04 UTC
deactivatezone2  Zone2       Inactive  DONE       17 Mar 19 20:04 UTC
```
