### ISSUE TITLE
`ApplicationClone` fails if namespace already exists

### ISSUE THREAD

**Issue by misterjoshua** [libopenstorage/stork#826]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
`ApplicationClone` fails if the destination namespace already exists. This repeats forever and the application clone never finishes:

```
time="2021-04-15T21:57:07Z" level=error msg="error creating destination namespace  dev-clone: <nil>" ApplicationCloneName=clone-dev-to-dev-clone-1618523746 Namespace=kube-system
time="2021-04-15T21:57:07Z" level=error msg="error creating destination namespace dev-clone: <nil>" ApplicationCloneName=clone-dev-to-dev-clone-1618523746 Namespace=kube-system
```

**What you expected to happen**:
The clone should succeed and overwrite the resources it finds in the namespace. This worked fine in `2.4.4`. From my testing, it works fine in `2.4.5`, but is broken in `2.5.0` and later, including `2.6.2` and `2.6.3`.

**How to reproduce it (as minimally and precisely as possible)**:
Create some workload in an ns named `dev`, then run `kubectl create ns dev-clone`.

Then apply this yaml:

```yaml
apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationClone
metadata:
    name: my-clone
    namespace: kube-system
spec:
    sourceNamespace: dev
    destinationNamespace: dev-clone
    replacePolicy: Delete
```

**Anything else we need to know?**:
We use `ApplicationClone` to promote software from dev to prod. We're stuck on 2.4 at the moment because of this.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.14
- Cloud provider or hardware configuration: Azure AKS
- OS (e.g. from /etc/os-release): Ubuntu 18.04.5 LTS (This is managed by Azure AKS)
- Kernel (e.g. `uname -a`): 5.4.0-1043-azure
- Install tools: Portworx 2.7, using Portworx Operator's StorageCluster resource with stork enabled
- Others: N/A
